title: Blog myusufkn
tagline: Catatan Seorang Pembelajar Web Development
description: Berisi catatan belajar Muhammad Yusuf dalam perjalanan memahami dunia teknologi dan kehidupan.
url: https://myusufkn.github.io
author:
  name: Muhammad Yusuf
  bio: Lulusan TKJ yang belajar Web Dev
  email: yusufmuhammad8899@gmail.com
