title: myusufkn
description: Berisi catatan belajar dalam perjalanan memahami dunia teknologi dan kehidupan.
tagline: Catatan seorang pelajar
url: https://myusufkn.github.io
author:
  name: Muhammad Yusuf
  bio: Masyarakat baru
